CREATE DATABASE  IF NOT EXISTS little_league_world_series;
USE little_league_world_series;
CREATE TABLE IF NOT EXISTS region_types (
    region_type_id INT AUTO_INCREMENT PRIMARY KEY,
    region_type_name VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS teams(
    team_id INT AUTO_INCREMENT PRIMARY KEY,
    team_name VARCHAR(100) NOT NULL,
    coach VARCHAR (100),
    region_type_id INT,
    FOREIGN KEY (region_type_id) REFERENCES region_types(region_type_id)

);

CREATE TABLE IF NOT EXISTS players (
    player_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    age INT CHECK (age BETWEEN 11 AND 13),
    primary_position VARCHAR(50),
    team_id INT,
    FOREIGN KEY ( team_id ) REFERENCES teams(team_id)
);

CREATE TABLE IF NOT EXISTS games (
    game_id INT AUTO_INCREMENT PRIMARY KEY,
    location VARCHAR(100),
    home_team_id INT NOT NULL,
    away_team_id INT NOT NULL,
    home_score INT,
    away_score INT,
    winning_team_id INT,
    losing_team_id INT,
    total_innings INT,
    attendance INT ,
    FOREIGN KEY (home_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (away_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (winning_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (losing_team_id) REFERENCES teams(team_id)
);
CREATE TABLE IF NOT EXISTS innings (
    inning_id INT AUTO_INCREMENT PRIMARY KEY,
    game_id INT NOT NULL,
    inning_number INT NOT NULL CHECK ( inning_number > 0),
    home_team_runs INT DEFAULT 0,
    away_team_runs INT DEFAULT 0,
    FOREIGN KEY (game_id) REFERENCES games(game_id),
    UNIQUE (game_id , inning_number)
);

CREATE TABLE IF NOT EXISTS player_game_batting (
    batting_id INT AUTO_INCREMENT PRIMARY KEY,
    player_id INT NOT NULL,
    game_id INT NOT NULL,
    team_id INT NOT NULL,
    at_bats INT DEFAULT 0,
    runs INT DEFAULT 0,
    hits INT DEFAULT 0,
    rbi INT DEFAULT 0, -- runs generated by a players hit
    doubles INT DEFAULT 0, -- getting to 2nd base
    triples INT DEFAULT 0, -- getting to third base
    home_runs INT DEFAULT 0, -- hitting out of the park
    walks INT DEFAULT 0, -- pitcher throws 4 balls
    strikeouts INT DEFAULT 0, -- 3 strikes
    stolen_bases INT DEFAULT 0,
    batting_avg DECIMAL(4,3) GENERATED ALWAYS AS
        (CASE WHEN at_bats > 0 THEN hits / at_bats ELSE 0 END) STORED,
    FOREIGN KEY (player_id) REFERENCES players(player_id),
    FOREIGN KEY (game_id) REFERENCES games(game_id),
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    UNIQUE (player_id, game_id)
);

CREATE TABLE IF NOT EXISTS player_game_pitching (
    pitching_id INT AUTO_INCREMENT PRIMARY KEY,
    player_id INT NOT NULL,
    game_id INT NOT NULL,
    team_id INT NOT NULL,
    innings_pitched DECIMAL(4,1) DEFAULT 0.0,
    hits_allowed INT DEFAULT 0,
    runs_allowed INT DEFAULT 0,
    earned_runs INT DEFAULT 0, -- from the data
    walks_allowed INT DEFAULT 0,
    strikeouts INT DEFAULT 0,
    home_runs_allowed INT DEFAULT 0,
    hit_batters INT DEFAULT 0,
    wild_pitches INT DEFAULT 0,
    pitches_thrown INT DEFAULT 0,
    strikes_thrown INT DEFAULT 0,
    win_loss_save CHAR(1) DEFAULT NULL,  -- 'W', 'L', or 'S'
    era DECIMAL(5,2) GENERATED ALWAYS AS
        (CASE WHEN innings_pitched > 0 THEN (earned_runs * 9) / innings_pitched ELSE 0 END) STORED,
    FOREIGN KEY (player_id) REFERENCES players(player_id),
    FOREIGN KEY (game_id) REFERENCES games(game_id),
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    UNIQUE (player_id, game_id)  -- one pitching record per player per game
);



